const mockEvents = {
  city: {
    id: 1007700,
    city: 'Muenchen',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257
  },
  events: [
    {
      created: 1562783371000,
      duration: 10800000,
      id: '263037278',
      name: 'Munich Frontend Developers Meetup Autumn Edition',
      rsvp_limit: 170,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1568910600000,
      local_date: '2019-09-19',
      local_time: '18:30',
      updated: 1562783381000,
      utc_offset: 7200000,
      waitlist_count: 13,
      yes_rsvp_count: 170,
      venue: {
        id: 26483775,
        name: 'Celonis SE',
        lat: 48.147335052490234,
        lon: 11.578679084777832,
        repinned: false,
        address_1: 'Theresienstraße 6',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1413460221000,
        name: 'Munich Frontend Developers',
        id: 17660862,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Frontend-Developers',
        who: 'Frontend Developers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-Frontend-Developers/events/263037278/',
      description: '<p>Welcome to Fronted Developers Meetup Autumn edition!<br/>This time we will be hosted by awesome guys from Celonis SE',
      how_to_find_us: 'Celonis SE',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1564048584000,
      duration: 10800000,
      id: '263449343',
      name: 'Kommunikation und Fehlerkultur in (agilen) Projekten',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1565020800000,
      local_date: '2019-08-05',
      local_time: '18:00',
      updated: 1564048610000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 56,
      venue: {
        id: 26292223,
        name: 'Mayflower GmbH',
        lat: 48.14387130737305,
        lon: 11.49881362915039,
        repinned: false,
        address_1: 'Landsberger Str. 314',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1463729812000,
        name: 'Rooftop Brains & BBQ',
        id: 19974719,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Rooftop-Brains-BBQ-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Rooftop-Brains-BBQ-Munich/events/263449343/',
      description: '<p>Dieses Meetup findet zwar außerhalb der Reihe statt – aber das tut dem Thema keinen Abbruch!</p> <p>„Das Problem ist somit nicht der Fehler, sondern der nicht entdeckte Fehler”, das ist eines der Leitbilder der Luftfahrt. Entscheidend dafür ist, den „Faktor Mensch” zu verstehen und dessen Verständnis für Fehler und Fehlerkultur zu schärfen.</p> <p>Der „Faktor Mensch” bezeichnet eine Vielzahl von Eigenschaften und Fähigkeiten, die es in einem Team zu koordinieren gilt: Ob das nun physische Eigenschaften wie die körperliche Konstitution oder das Alter oder Soft Skills wie Kommunikationsfähigkeit sind – am Ende müssen alle an einem Strang ziehen.</p> <p>Diese Human Factors sind unabhängig vom Fachgebiet überall zu finden wo Menschen handeln. In kritischen Situationen können sie entscheidenden Einfluss auf die Lösung einer Situation haben und sind maßgeblich für Erfolg oder Misserfolg verantwortlich – das gilt auch für agile Teams.</p> <p>In diesem Vortrag setzt Steffen die Fehlerkultur und Kommunikationsmethoden aus der Luftfahrt in den Kontext unseres täglichen Projektgeschäfts und zeigt, wie wir damit noch besser werden können.</p> ',
      how_to_find_us: 'Du findest uns im fünften Stock auf der rechten Seite',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1563200079000,
      duration: 7200000,
      id: '263164979',
      name: 'SUMMER EVENT - Fast and Furious serverless',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1564590600000,
      local_date: '2019-07-31',
      local_time: '18:30',
      updated: 1563987844000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 69,
      venue: {
        id: 26213431,
        name: 'Saxonia Systems AG',
        lat: 48.094970703125,
        lon: 11.525230407714844,
        repinned: false,
        address_1: 'Kistlerhofstraße 75',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1473068565000,
        name: 'Serverless Munich',
        id: 20389664,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Serverless-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Serverless-Munich/events/263164979/',
      description: '<p>[Hot July Events - Part2]<br/>As promised we will do a community event this month too.<br/>Which let us dive into the speedy Nuclio and the world of async serverless websockets.</p> <p>[Agenda]</p> <p>1. “High-Performance FaaS with Nuclio” - Mario-Leander Reimer</p> <p>Not long ago, the advent of microservice architectures was a big disruption in software engineering: systems were now build, composed and run as autonomous services. But this came at the price of added complexity. Serverless and FaaS seem to be the next disruption, they are the logical evolution in cloud native software development.</p> <p>Of course, FaaS bringt its own set of challenges, such as cold startup performance, asynchronism and overall throughput. But it does not have to be all that bad. Do you want to know what real fast FaaS looks like? Then fasten your seatbelts when we give Nuclio a try.</p> <p>2. “Serverless Websocket APIs with Lambda &amp; API Gateway ” - Leo Lindhorst</p> <p>WebSockets provide a way to asynchronously publish events from the backend to Web-based clients, which is an important capability when combining Web Apps with event-driven backend architectures. But when building a completely Serverless backend it was a challenge for a long time to support long-living and stateful connections with short-living, event-driven Lambda Functions. Since re:invent 2018 AWS offers the possibility of building Lambda-backed WebSocket APIs using AWS API Gateway, which provide an easy solution for this problem. This talk gives an introduction to WebSockets and API Gateway WebSocket APIs and show how to get started with this powerful tool.</p> <p>3. Of course networking by a beer ^^</p> <p>[Call for speakers]<br/>As this whole meetup is driven by the community, we always eager to here more what your experiences and questions are.<br/>No matter how big or small it is, share it with us</p> ',
      how_to_find_us: 'Take the main entry and just walk straight to the reception desk. On the left hand side you’ll find a glass door. Pass it and take the elevator to the 5th floor.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '19:00',
      local_date: '2019-09-17',
      link: 'https://www.meetup.com/Software-Performance-Meetup-Group/events/262807509/',
      visibility: 'public_limited',
      group: {
        created: 1400662449000,
        name: 'Software Performance Meetup Group',
        id: 14586172,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Software-Performance-Meetup-Group',
        who: 'Performance Management Worker',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      waitlist_count: 0,
      yes_rsvp_count: 65,
      duration: 10800000,
      time: 1568739600000,
      utc_offset: 7200000,
      name: '20th Software Performance Meetup',
      id: '262807509'
    },
    {
      created: 1562057073000,
      duration: 7200000,
      id: '262805286',
      name: 'Testing your code and your tests',
      rsvp_limit: 40,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566405000000,
      local_date: '2019-08-21',
      local_time: '18:30',
      updated: 1562354982000,
      utc_offset: 7200000,
      waitlist_count: 26,
      yes_rsvp_count: 40,
      venue: {
        id: 26182777,
        name: 'innoQ Deutschland GmbH',
        lat: 48.135284423828125,
        lon: 11.567602157592773,
        repinned: true,
        address_1: 'Kreuzstraße 16',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1344375043000,
        name: 'Munich Scala User Group',
        id: 4493412,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'ScalaMuc',
        who: 'Scalaphiles',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/ScalaMuc/events/262805286/',
      description: '<p>In this meetup, we will talk about testing! INNOQ will provide food &amp; drinks.</p> <p>Schedule:<br/>18:30 Doors open<br/>19:15 Daniel Westheide<br/>20:00 Break<br/>20:15 Lars Hupel</p> <p>Daniel Westheide: Testing in the postapocalyptic future<br/>',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1564057142000,
      duration: 7200000,
      id: '263450824',
      name: 'Intro to Azure Kubernetes Service and Azure Container Registry',
      rsvp_limit: 50,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1567096200000,
      local_date: '2019-08-29',
      local_time: '18:30',
      updated: 1564057150000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 35,
      venue: {
        id: 25766821,
        name: 'medialesson - Büro München',
        lat: 48.153099060058594,
        lon: 11.583580017089844,
        repinned: false,
        address_1: 'Leopoldstr. 8-10',
        address_2: 'c/o Nutrion Coworking Space',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1520252901000,
        name: 'Software, Technology & Design Meetup München',
        id: 27731423,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Software-Technology-Meetup-Munchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Software-Technology-Meetup-Munchen/events/263450824/',
      description: '<p>In this session we\'ll go beyond hello world – what you need to know to run real apps on the most popular container orchestrator n Azure.</p> <p>We’ll review a high-level overview of the Azure Kubernetes Service (AKS) service and Azure Container Registry (ACR). We will start with the basic concepts of Kubernetes followed by understanding how AKS is different from the vanilla Kubernetes.<br/>Finally we\'ll be setting up and deploying a real world app on AKS. Feel free to follow along!</p> <p>About the speaker:<br/>Mohit Chhabra is working as Software Engineer at medialesson GmbH, Germany. He is currently Microsoft Most Valuable Professional for Microsoft Azure and former leader of BDotnet (India\'s Biggest offline community). He has deliver more than 50 sessions in the community and international conferences. Prior to this, Mohit was Microsoft Student Partner and Mozilla Student Representative. He was also India\'s first Azure Champion and first person to intern in Microsoft Technology Center.</p> <p>This meetup will be hosted by medialesson, food and drinks will be provided. Please make sure you update your RSVP status 24h in advance so we don\'t waste any food!</p> <p>This is another meetup we\'re doing together with the Azure DEV Meetup Munich. Check it out for more Azure-related Meetups :',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '18:00',
      local_date: '2019-08-08',
      link: 'https://www.meetup.com/Female-Coders-Lab-Munchen/events/263359334/',
      visibility: 'public_limited',
      group: {
        created: 1554408399000,
        name: 'Female Coders Lab (München)',
        id: 31557493,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Female-Coders-Lab-Munchen',
        who: 'Coders',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      waitlist_count: 0,
      yes_rsvp_count: 8,
      duration: 9000000,
      time: 1565280000000,
      utc_offset: 7200000,
      name: 'Study Group @ ThoughtWorks',
      id: '263359334'
    },
    {
      created: 1563023071000,
      duration: 7200000,
      id: '263119080',
      name: 'August Meetup - Philosophy & Physics',
      rsvp_limit: 80,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1565109000000,
      local_date: '2019-08-06',
      local_time: '18:30',
      updated: 1563448862000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 63,
      venue: {
        id: 26292223,
        name: 'Mayflower GmbH',
        lat: 48.14387130737305,
        lon: 11.49881362915039,
        repinned: true,
        address_1: 'Landsberger Str. 314',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1372413211000,
        name: 'Munich Lambda',
        id: 9128172,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Lambda',
        who: 'Hackers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-Lambda/events/263119080/',
      description: '<p>For our next meetup, we\'ll have two speakers using ClojureScript and Haskell to introduce us to some physical and philosophical questions that can be modeled with functional programming.</p> <p>Please be aware that the latter talk on 18th century philosopher Immanuel Kant\'s categorical imperative will be a mix of German and English. Code examples will likely help, and I\'m sure the German speaking audience will provide clarifications for the people next to them.</p> <p>Mayflower has kindly agreed to provide us with beverages and freshly grilled barbecue on their lovely new roof terrace. Carnivore, vegetarian and vegan options will be available!</p> <p>Location: Mayflower GmbH</p> <p>Agenda:<br/>18:30 - Meet and greet with food and drinks<br/>19:00 - Thomas Sojka: The discovery of fire in ClojureScript<br/>19:30 - Questions and discussion<br/>19:45 - Cornelius Diekmann: Kants kategorischer Imperativ in Haskell [partially GERMAN!]<br/>20:15 - Questions and discussion<br/>20:30 - End</p> <p>Talk info:<br/>Title: The discovery of fire in ClojureScript<br/>Language: English<br/>Speaker: Thomas Sojka<br/>',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1556284315000,
      duration: 7200000,
      id: '260941484',
      name: 'Pitch Club Developer Edition #36',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1571335200000,
      local_date: '2019-10-17',
      local_time: '20:00',
      updated: 1556284315000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 25959917,
        name: 'Bar Ludwig II',
        lat: 48.12186813354492,
        lon: 11.58230972290039,
        repinned: true,
        address_1: 'Hochstraße 77',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1539021073000,
        name: 'Pitch Club Developer Edition München',
        id: 30141555,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Pitch-Club-Developer-Edition-Munchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Pitch-Club-Developer-Edition-Munchen/events/260941484/',
      description: '<p>Softwareentwickler und IT-Professionals aufgepasst! Pitch Club veranstaltet am 17. Oktober 2019 ab 17 Uhr in der Bar Ludwig II (Hochstraße 77, 81541 München) die “Pitch Club Developer Edition #36” in München. Hierfür suchen wir noch Entwickler und Projektmanager aus dem IT-Bereich, die an dem Event teilnehmen möchten.</p> <p>Beim Event treffen gestandene Unternehmen und Startups auf IT-Professionals, die es zu überzeugen gilt. Die Unternehmen pitchen ihr HR-Konzept, Jobs und Projekte und versuchen so, die Talente für sich zu gewinnen. Die Entwickler stellen zudem unbequeme Fragen und prüfen die Jobs auf Herz und Nieren. Am Ende müssen die Unternehmen in 1-on-1 Gesprächen nochmal alles geben, bei der alle Teilnehmer sich bei Speisen und Getränken austauschen und gegebenenfalls schon mit ihren zukünftigen Arbeitgebern in Kontakt treten können. Nach Abschluss der Veranstaltung geht das Event ab 20 Uhr in die öffentliche Afterwork Party über.</p> <p>Wenn Du an der kostenlosen Teilnahme (inklusive Snackbuffet, Softdrinks, Bier und Long Drinks) beim invite-only Event ab 17 Uhr interessiert bist, dann bewirb Dich unter',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1563804419000,
      duration: 381600000,
      id: '263359154',
      name: 'International JavaScript Conference',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1571641200000,
      local_date: '2019-10-21',
      local_time: '09:00',
      updated: 1563805194000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 9,
      venue: {
        id: 26495814,
        name: 'Holiday Inn München - Stadtzentrum',
        lat: 48.13060760498047,
        lon: 11.589520454406738,
        repinned: true,
        address_1: 'Hochstraße 3',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1497515784000,
        name: 'International JavaScript Conference',
        id: 24474394,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'International-JavaScript-Conference',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/International-JavaScript-Conference/events/263359154/',
      description: '<p>Angular, React, Vue.js, NativeScript, Electron, Node.js: Find out how to use JavaScript from front end to back end, for native mobile, desktop apps, and even cloud native development. Our renowned experts at International JavaScript Conference will bring you the latest trends and cutting-edge technologies in JavaScript and enhance your JS knowledge where it matters.</p> <p>JavaScript is everywhere! Meet us in Munich this October to join our exciting sessions and workshops and take your JS skills to the next level.</p> <p>Visit our website for more info: ',
      how_to_find_us: 'https://javascript-conference.com/',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1553586603000,
      duration: 10800000,
      id: 'qzjdvqyzlbcc',
      name: 'Drupal Meetup',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566406800000,
      local_date: '2019-08-21',
      local_time: '19:00',
      updated: 1553586604000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      group: {
        created: 1410086988000,
        name: 'München Drupal User Group Meetup',
        id: 16845232,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Drupal-User-Group-Meetup',
        who: 'Drupalistas',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munchen-Drupal-User-Group-Meetup/events/qzjdvqyzlbcc/',
      description: '<p>Jeden dritten Mittwoch im Monat treffen wir uns zum Drupal-Meetup entweder im EineWeltHaus oder bei eine Unternehmen. Das Meetup ist für Drupal-Anwender, -Entwickler, -Einsteiger aber auch -Professionals geeignet. Wir reden aber nicht nur über Drupal, sondern auch über Community, React, Vue.js, Docker, Symfony, PHP, UX und viele andere Dinge. Deshalb sind andere Communities bei uns herzlich willkommen.</p> <p>Every third wednesday we come together for a Drupal meetup either in the EineWeltHaus or hosted by a company. The meeetup is for any level of Drupal user. We are not talking Drupal only but also about community, React, Vue.js, Docker Symfony, PHP, UX and much more stuff. For this other communities are very welcome.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1371224928000,
      duration: 7200000,
      id: 'drpzdgyzlbsb',
      name: 'Ruby User Group Meetup',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1565802000000,
      local_date: '2019-08-14',
      local_time: '19:00',
      updated: 1559576853000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 7,
      venue: {
        id: 23568476,
        name: 'Park Café',
        lat: 48.14232635498047,
        lon: 11.56459903717041,
        repinned: false,
        address_1: 'Sophienstraße 7',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1370808069000,
        name: 'Munich Rubyshift, Ruby User Group',
        id: 8851722,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Rubyshift-Ruby-User-Group',
        who: 'Rubyists',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-Rubyshift-Ruby-User-Group/events/drpzdgyzlbsb/',
      description: '<p>August will be our traditional Beergarden Meetup!<br/>We will meet at Park Café Sophienstraße – everybody is welcome. Rest assured, the beer garden will also serve pretty tasty non-alcoholic beverages!</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1371224928000,
      duration: 7200000,
      id: 'drpzdgyzmbpb',
      name: 'Ruby User Group Meetup',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1568221200000,
      local_date: '2019-09-11',
      local_time: '19:00',
      updated: 1563180653000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26377974,
        name: 'xbAV AG',
        lat: 48.14632034301758,
        lon: 11.537505149841309,
        repinned: true,
        address_1: 'Arnulfstraße 126',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1370808069000,
        name: 'Munich Rubyshift, Ruby User Group',
        id: 8851722,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Rubyshift-Ruby-User-Group',
        who: 'Rubyists',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-Rubyshift-Ruby-User-Group/events/drpzdgyzmbpb/',
      description: '<p>Pascal Wengerter – Fullstack Web Development in pure Ruby with Matestack::Ui::Core</p> <p>We\'re actively searching for speakers! Want to become one? Ping us!</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1544737311000,
      duration: 10800000,
      id: '257197534',
      name: 'Drinks and Talks at LINKS DER ISAR',
      rsvp_limit: 31,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1568307600000,
      local_date: '2019-09-12',
      local_time: '19:00',
      updated: 1544737311000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 12,
      venue: {
        id: 24013151,
        name: 'LINKS DER ISAR',
        lat: 48.14236831665039,
        lon: 11.584701538085938,
        repinned: true,
        address_1: 'Seitzstraße 23 80538 ',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1391254650000,
        name: 'Laravel Usergroup Munich',
        id: 12659962,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'laravel-munich',
        who: 'Artisans',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/laravel-munich/events/257197534/',
      description: '<p>Dear all,</p> <p>If you have any projects or talks that you want to share with the community, feel free to drop Alex or me a line.</p> <p>The meetup will start as usual at 19.00h with drinks, pizza and networking. The presentation (tba.) will start at 19.30h. Please make sure to come early.</p> <p>Looking forward to an awesome evening. As always, we\'re happy to host developers of any skill: From newbies to experts, everyone is welcome.</p> <p>All the best<br/>Philipp</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1562869645000,
      duration: 10800000,
      id: '263069546',
      name: 'Scrum Speakers @ LV 1871',
      rsvp_limit: 50,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1565109000000,
      local_date: '2019-08-06',
      local_time: '18:30',
      updated: 1564142210000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 29,
      venue: {
        id: 26021892,
        name: 'Lebensversicherung von 1871 a. G. München (LV 1871)',
        lat: 48.14217758178711,
        lon: 11.570405006408691,
        repinned: true,
        address_1: 'Maximilianspl. 5',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1558423773000,
        name: 'Scrum Speakers',
        id: 31977973,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'ScrumSpeakers',
        who: 'Scrum Speakers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/ScrumSpeakers/events/263069546/',
      description: '<p>Speech topics: Big room planning, OKR</p> <p>Agenda:</p> <p>18:30 Gather and settle down<br/>19:00 Opening</p> <p>19:10 OKR Objekt and Key Results | Deutsch | Martin Messerer | Scrum Master</p> <p>19:35 Stakeholders... the gold in the differences | English | Michael Graham | Stakeholder</p> <p>20:00 Break</p> <p>20:15 Unsere Schlachtplan Konferenz (Big Room Planning) | Deutsch | Marianne Spiel | Product Owner für Bestandsführung bei der LV 1871</p> <p>20:40 English | Developer | TBD</p> <p>21:05 Closing</p> <p>21:30 End</p> <p>Note: Food and drinks available for the Scrum Speakers</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1562311270000,
      duration: 381600000,
      id: '262891231',
      name: 'International PHP Conference 2019',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1571637600000,
      local_date: '2019-10-21',
      local_time: '08:00',
      updated: 1562311270000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26495814,
        name: 'Holiday Inn München - Stadtzentrum',
        lat: 48.13060760498047,
        lon: 11.589520454406738,
        repinned: false,
        address_1: 'Hochstraße 3',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1381480743000,
        name: 'International PHP Conference 2019',
        id: 10644212,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'PHPConference',
        who: 'Members',
        localized_location: 'Berlin, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/PHPConference/events/262891231/',
      description: '<p>With over a decade’s experience, the International PHP Conference is the must-attend event for web developers from around the globe. Attend inspiring sessions, unique in-depth workshops, and benefit from our experts’ invaluable insights!<br/>At IPC, discover the exciting interaction of PHP with technologies such as Symphony, Docker and Kubernetes, as well as JavaScript and TypeScript. You’ll also learn about the newest features in PHP 7, plenty of groundbreaking tools, test automation, cutting edge web security tactics, and state-of-the-art web architectures.<br/>Get ready to benefit from innovative approaches and valuable insights from IPC’s outstanding speakers. Gain a real competitive advantage for your projects in a rapidly changing digital age.<br/>',
      how_to_find_us: 'Hochstraße 3,81669 Munich, Telefon: +49 89 4803-0, Telefax: +49 89 4488 277, E-Mail: hi.muenchen@whgeu.com',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1563390428000,
      duration: 7200000,
      id: '263233361',
      name: 'Dynamic Imports',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1567098000000,
      local_date: '2019-08-29',
      local_time: '19:00',
      updated: 1563390428000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 8,
      venue: {
        id: 23629210,
        name: 'HolidayCheck',
        lat: 48.13277053833008,
        lon: 11.624322891235352,
        repinned: true,
        address_1: 'Neumarkter Str. 61',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1443104684000,
        name: 'JavaScript The Language',
        id: 18963486,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'JavaScript-The-Language',
        who: 'JavaScripter',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/JavaScript-The-Language/events/263233361/',
      description: '<p>This meetup will be very hands on, no presentations - just talking, thinking, coding and sharing.</p> <p>This time we will handle dynamic imports which are already usable in many places like node and v8. We will analyze the features in depth, discuss and code. This topic is also perfect to dive deep into the spec [1]. So we can figure out where things are defined and try to understand from the spec and our tests how they work.</p> <p>[1]:',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1536308315000,
      duration: 30600000,
      fee: {
        accepts: 'cash',
        amount: 20,
        currency: 'EUR',
        description: 'per person',
        label: 'Price',
        required: false
      },
      id: 'tcdgfqyzlbcb',
      name: 'Drupal Coworking Day',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1564642800000,
      local_date: '2019-08-01',
      local_time: '09:00',
      updated: 1536308315000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 19782872,
        name: 'WERK1',
        lat: 48.12442398071289,
        lon: 11.607309341430664,
        repinned: true,
        address_1: 'Grafinger Straße 6',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1410086988000,
        name: 'München Drupal User Group Meetup',
        id: 16845232,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Drupal-User-Group-Meetup',
        who: 'Drupalistas',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munchen-Drupal-User-Group-Meetup/events/tcdgfqyzlbcb/',
      description: '<p>Wir treffen uns einmal im Monat zu einem ungezwungen Coworking-Tag. Jeweils am ersten Donnerstag im Monat bietet uns dafür das Werk1 eine schöne Atmosphäre um uns in die Arbeit zu vertiefen aber auch nebenbei über Drupal-nahe und -fremde Themen zu sprechen.</p> ',
      how_to_find_us: 'Eingang zum Coworking-Berech über das Werk1.Café',
      visibility: 'public',
      member_pay_fee: false
    }
  ]
}

export { mockEvents }
